#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Weaving the Web

# Short bio or description (displayed in the header)
description: Schwerpunkt im Medieninformatik Master

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://www.medieninformatik.th-koeln.de/img/mi-box-100.png

# Where are we?
timezone: Europe/Berlin

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://th-koeln.github.io/
deployurl: https://th-koeln.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/mi-master-wtw" # the subpath of your site, e.g. /blog
# baseurl: "/th-koeln-mi-boilerplate" # the subpath of your site, e.g. /blog

# Set hero background image options
# heroimage: image file from the assets/images folder
# heroimage_contain: should the background image have the contain css size option
# heroimage_size: size of the hero area. Options are large, medium or null for small
heroimage: "hero-wtw-klein.jpg"
heroimage_contain: false
heroimage_size: "medium"

# Edit items in the navigation here
# Use path for links in this site and url for exernal links
navigation:
  - path: timetable-sose-2019/
    name: Zeitplan SoSe 2019
  - path: web-technologien/
    name: Web Technologien
  - path: formate/
    name: Formate
  - url: https://github.com/th-koeln/mi-master-wtw/issues/new
    name: Frage stellen
  - url: https://github.com/th-koeln/mi-master-wtw/wiki
    name: WTW Wiki

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# be sure that you use kramdown as markdown processor
markdown: kramdown

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  extensions: [footnotes]
  footnote_location: 'my_footnotes'
  parse_block_html: true
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Zur Abtrannung der Aufgabe
excerpt_separator: "<!--aufgabe-->"

# Use the following plug-ins
plugins_dir:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Build settings
remote_theme: flobraeun/mi-jekyll-theme
theme: mi-jekyll-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

collections:
  webtechnologien:
    output: false
  lehrveranstaltungen:
    output: true
  workshops:
    output: true
  faq:
    output: false
  snippets:
    output: false
  links:
    output: false
  news:
    output: false

defaults:
  -
    scope:
      path: ""
      type: lehrveranstaltungen
    values:
      layout: lehrveranstaltung
  -
    scope:
      path: ""
      type: faq
    values:
      layout: faq
